-- Preload the projects already vetted as TRUE by the discovery scan.
-- Regenerated by scripts/refresh-seed.mjs - do not edit by hand.
-- Idempotent: re-running refreshes the profile fields of existing rows.
insert into public.nft_projects (
  handle, name, avatar, banner, bio, followers, following, verified, joined,
  is_nft_project, status, processed, discovered_at, added_at, processed_at
)
values
  ('the_tempagency', 'temp agency', 'https://pbs.twimg.com/profile_images/2087337260177862656/NDiGE5k3_400x400.jpg', 'https://pbs.twimg.com/profile_banners/2087335262732869632/1786563761', '2222 - free mint - no wl 

stay tuned', 633, 13, false, 'Wed Aug 12 00:34:24 +0000 2026', true, 'added', true, now(), now(), now()),
  ('moankeeauction', 'Moankee Auction Club', 'https://pbs.twimg.com/profile_images/2088409134156611584/VOxUWrC1_400x400.jpg', 'https://pbs.twimg.com/profile_banners/2086882646706077698/1786387287', 'Coming soon to @robinhoodapp
Stake. Earn auction points. Bid and win.', 505, 21, false, 'Mon Aug 10 18:34:16 +0000 2026', true, 'added', true, now(), now(), now()),
  ('nibblinsnft', 'Nibblins', 'https://pbs.twimg.com/profile_images/2088324921130672128/DbxxNuOW_400x400.jpg', 'https://pbs.twimg.com/profile_banners/2088323405451841536/1786730445', 'A new world of little creatures. All Nibblins. Coming to Robinhood.', 20, 2, false, 'Fri Aug 14 17:56:25 +0000 2026', true, 'added', true, now(), now(), now()),
  ('miu_nft', 'MIU | FREEMINT', 'https://pbs.twimg.com/profile_images/2088334232791752704/4yICfHiq_400x400.jpg', 'https://pbs.twimg.com/profile_banners/2088329183298490368/1786731908', '4000 Kawai Miu | Free mint launch on @RobinhoodApp', 32, 6, false, 'Fri Aug 14 18:21:03 +0000 2026', true, 'added', true, now(), now(), now()),
  ('glorprbh', 'Glorp', 'https://pbs.twimg.com/profile_images/2087624522643935232/2-MhsFEQ_400x400.jpg', 'https://pbs.twimg.com/profile_banners/2087619016961503232/1786562467', 'landing soon on RBH 🛸', 923, 13, false, 'Wed Aug 12 19:17:57 +0000 2026', true, 'added', true, now(), now(), now())
on conflict ((lower(handle))) do update set
  name = excluded.name,
  avatar = excluded.avatar,
  banner = excluded.banner,
  bio = excluded.bio,
  followers = excluded.followers,
  following = excluded.following,
  verified = excluded.verified,
  joined = excluded.joined,
  status = excluded.status,
  processed = excluded.processed,
  updated_at = now();
